### PR TITLE
Convert to cmake for Windows, Linux and Mac

### LINKED ISSUE #24: Windows, Mac, Ubuntu (multiplatform) version
I would like to contribute multiple things to this project. My first contrib is a windows version.

To do this I made a major change. I converted the build system to cmake. This is way more convenient than the autoconf, automake etc.

I fixed a few non portability issues.

I also change how googletest gets run. I followed their instructions for cmake integration - https://google.github.io/googletest/quickstart-cmake.html

It now builds and runs on windows vs2022, ubuntu gcc, and mac clang M1 ( I dont have an intel mac)

Would you like to take a look at the PR

### PR DESCRIPTION
**Pull request by pm100**
Sorry - I am not the worlds greatest git / github expert. I have ended up with many commits for this change. Its how I share my local repro with windows, linux and mac. Probably better ways to do it :-)

Explanation of changes

Main change, convert from autoconf, configure,... to cmake. This allows one build on all platforms. I have tested with Windows 11 and vs2022, ubuntu with gcc and Mac with clang

One slight issue is that the cmake installed by default on ubuntu is pretty old, so there are a few fiddly bits to deal with this

fixed various portability / compiler warnings

 - include bits/stdc++ is non standard and non portable
 - the lack of virtual destructor crashed the tests on Mac
 - vs2022 complained about size_t vs int and unused exception variables

I added an environment variable to override the location of extdata. This is because the relative location of the cnh binary and extdata varies depending on the build platform. So it was hard to test (including running the tests). CNH_EXTDATA is it name

I updated the readme to show how to build etc

I removed all the old makefiles, configure.ac etc. etc.

Note that cmake builds makefiles for you so you can still run make is you want. I find it easier to use cmake --build tho since its the same on all platforms

### CODE REVIEW

**Comment by alucardthefish** [comment]
Hi @pm100 Awesome contribution! I will review it as soon as I can.

**Comment by alucardthefish** [comment]
hi @pm100 
I've been checking this PR, but I'm facing an issue when following the build on win10. This is the error:

```bash
-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:2 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

CMake Error: Generator: execution of make failed. Make command was: nmake -f Makefile /nologo &&
```

I try running it by passing my compiler info like this:
```bash
cmake -DCMAKE_CXX_COMPILER=C:/msys64/mingw64/bin/g++ -DCMAKE_C_COMPILER=C:/msys64/mingw64/bin/gcc -B build -S .
```
but got same error without compiler errors. Do you know how to solve this?

**Comment by pm100** [comment]
Sounds like you do not have vs 2022 installed with the c++ support.

What toolchain is installed?

**Comment by pm100** [comment]
You can install vs2022 free version here Visual Studio 2022 Community Edition - Download Latest Free Version (microsoft.com)<https://visualstudio.microsoft.com/vs/community/>

Its what I use

**Comment by pm100** [comment]
ok i see you are using mingw64. You should not set those compiler flags yourself, you need to tell cmake what toolchain to use at a higher level - although it should detect it.

I will invetigate

**Comment by pm100** [comment]
well here are the instructions. I dont know msys2 very well (used a few years ago).

https://www.msys2.org/docs/cmake/

I will have a go at it

**Comment by pm100** [comment]
I installed msys2, devtools (which includes cmake) and git. Builds fine using the linux_debug.sh script inside msys2 shell.

I assume the issue is that you ran the win_xxx.cmd script in a non msys2 shell.


$ cat linux_debug.sh
cmake -Bdebug -DCMAKE_BUILD_TYPE=Debug
cmake --build debug
pushd ./debug/tests
ctest
popd
paulm@paul-think MSYS ~/cnh/CodeNowHere
$ . ./linux_debug.sh
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Python (missing: Python_EXECUTABLE Interpreter)
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done (6.3s)
-- Generating done (0.4s)
-- Build files have been written to: /home/paulm/cnh/CodeNowHere/debug
[  4%] Building CXX object src/CMakeFiles/cnh.dir/__/Main.cpp.o
[  8%] Building CXX object src/CMakeFiles/cnh.dir/BunchFileBehavior.cpp.o
[ 12%] Building CXX object src/CMakeFiles/cnh.dir/CodeNowHere.cpp.o
[ 16%] Building CXX object src/CMakeFiles/cnh.dir/Helper.cpp.o
[ 20%] Building CXX object src/CMakeFiles/cnh.dir/ICommandBehavior.cpp.o
[ 25%] Building CXX object src/CMakeFiles/cnh.dir/ManyFileBehavior.cpp.o
[ 29%] Building CXX object src/CMakeFiles/cnh.dir/OnlyFileBehavior.cpp.o
[ 33%] Building CXX object src/CMakeFiles/cnh.dir/cnh_structs.cpp.o
[ 37%] Building CXX object src/CMakeFiles/cnh.dir/docopt.cpp.o
[ 41%] Linking CXX executable ../cnh.exe

**Comment by alucardthefish** [comment]
> I installed msys2, devtools (which includes cmake) and git. Builds fine using the linux_debug.sh script inside msys2 shell.
> 
> I assume the issue is that you ran the win_xxx.cmd script in a non msys2 shell.
> 
> $ cat linux_debug.sh cmake -Bdebug -DCMAKE_BUILD_TYPE=Debug cmake --build debug pushd ./debug/tests ctest popd paulm@paul-think MSYS ~/cnh/CodeNowHere $ . ./linux_debug.sh -- The C compiler identification is GNU 11.3.0 -- The CXX compiler identification is GNU 11.3.0 -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Check for working C compiler: /usr/bin/cc.exe - skipped -- Detecting C compile features -- Detecting C compile features - done -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Check for working CXX compiler: /usr/bin/c++.exe - skipped -- Detecting CXX compile features -- Detecting CXX compile features - done -- Could NOT find Python (missing: Python_EXECUTABLE Interpreter) -- Performing Test CMAKE_HAVE_LIBC_PTHREAD -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success -- Found Threads: TRUE -- Configuring done (6.3s) -- Generating done (0.4s) -- Build files have been written to: /home/paulm/cnh/CodeNowHere/debug [ 4%] Building CXX object src/CMakeFiles/cnh.dir/__/Main.cpp.o [ 8%] Building CXX object src/CMakeFiles/cnh.dir/BunchFileBehavior.cpp.o [ 12%] Building CXX object src/CMakeFiles/cnh.dir/CodeNowHere.cpp.o [ 16%] Building CXX object src/CMakeFiles/cnh.dir/Helper.cpp.o [ 20%] Building CXX object src/CMakeFiles/cnh.dir/ICommandBehavior.cpp.o [ 25%] Building CXX object src/CMakeFiles/cnh.dir/ManyFileBehavior.cpp.o [ 29%] Building CXX object src/CMakeFiles/cnh.dir/OnlyFileBehavior.cpp.o [ 33%] Building CXX object src/CMakeFiles/cnh.dir/cnh_structs.cpp.o [ 37%] Building CXX object src/CMakeFiles/cnh.dir/docopt.cpp.o [ 41%] Linking CXX executable ../cnh.exe

Hi @pm100 Yes, I was executing win_release.cmd file from regular CMD. So should I use the linux_debug.sh in a msys2 shell? 

Sorry, I'm a big newbie to cmake, msys2, development of c++ on Win.

**Comment by pm100** [comment]
You have 2 choices

Use msys2

Use visual studio

Vs is the way to go as far as I am concerned. It's real windows not a sorta unix, sorta windows thing.

Vs community edition is free. Supports c, c++, c#... It's the best c++ ide I think. There is a link to install it earlier

________________________________

**Comment by alucardthefish** [comment]
@pm100 Sure, I will install it and let you know. Thanks.

**Review by alucardthefish — APPROVED** [review]
Approved.

**Comment by alucardthefish** [comment]
Hi @pm100
I have tested your changes on Win10 with VS2022 as you recommended to me and on Linux Ubuntu with g++ working as expected. I really appreciate your efforts on this enhancement. Thank you 🚀 👍🏼 💯

**Pull request merged**
