### PR TITLE
Order lines alphabetically + add C-Intercal

### LINKED ISSUE #1: Add support for more programming languages
### Supporting more programming languages

Base in the contribution flow and steps present [here](https://github.com/firstcontributions/first-contributions) create your branch and start contributing.

First check that the language you want to add is not already in the file.

You can edit the extdata/lang.dat file; adding new programming language file extensions using the following format:
append below the last line of the file
<pre>
.ext1 .ext2 .extN : nameoflanguage
</pre>
for instance:
`.rb .rbw : ruby`

Then you can edit extdata/inlineComments.txt. There you can add the extensions according to inline comment character(s). It follows the same convention like before, but after the colon is now the inline comment character(s) specified instead of nameoflanguage.

for instance:
if another language extensions uses the same inline comment, then add them next to it.
`.py .pyc .pyo .pyd .php .rb .rbw : # {}`
otherwise, create a new line below the last line this way:
`.rb .rbw : # {}`

The `{}` specifies the closing comment character is not required. But in a language that is required such html you could set it like this:
`.html .htm : <!-- -->`

Then, you have to create a new file named nameoflanguage.tpl (nameoflanguage must be the same as it was in inlineComments.txt). Open it and write in the first line a sample code of line printing "Hello World" or a main function/method that prints the well known message "Hello World" too.

Finally, do not forget to write the new language into the alphabetically ordered list in README section. 

You can create a PR with a message saying what language you are adding.

### PR DESCRIPTION
**Pull request by CGS-Jack-Bashford**
I reorded the liens in this file alphabetically - both so it's easier to find issues, and to insert new extensions if necessary. I also added a new language to the list - C-Intercal (.i file extension)

### Description

Fixes #1 

### Type of Change:

- Code:
    - [x] Bug fix (non-breaking change which fixes an issue)
    - [x] New feature (non-breaking change which adds functionality pre-approved by consensus
- Documentation
### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged

### CODE REVIEW

**Comment by alucardthefish** [comment]
Hi @CGS-Jack-Bashford thanks for contrib. The PR does not correspond to the issue related. You must have followed the steps. In total you need to edit 3 files and create 1 to PR the issue #1 

Feel free to make the changes and commits to this PR.

Thanks

**Comment by CGS-Jack-Bashford** [comment]
@alucardthefish Fixed those issues :)

**Comment by alucardthefish** [comment]
@CGS-Jack-Bashford  Thanks for contributing to this project!

**Comment by CGS-Jack-Bashford** [comment]
@alucardthefish Just out of curiosity - I actually found this project through a Hacktoberfest website. Seeing as this repository would be a great option for those new to open source and who want to contribute, would you be able to add the hacktoberfest topic to this repository (or even the hacktoberfest-accepted tag to this PR)? I understand if you don't want to, but I would love it if this contribution (which involved a fairly difficult esoteric language :P) was accepted into Hacktoberfest. Thank you in advance for your consideration!

**Comment by alucardthefish** [comment]
> @alucardthefish Just out of curiosity - I actually found this project through a Hacktoberfest website. Seeing as this repository would be a great option for those new to open source and who want to contribute, would you be able to add the hacktoberfest topic to this repository (or even the hacktoberfest-accepted tag to this PR)? I understand if you don't want to, but I would love it if this contribution (which involved a fairly difficult esoteric language :P) was accepted into Hacktoberfest. Thank you in advance for your consideration!

Hi, how can I add the tag?

**Comment by alucardthefish** [comment]
@CGS-Jack-Bashford I've researched a bit and I think I got it. BTW I didn't know how the hacktoberfest thing works! Hope the label helps you!

**Pull request merged**
